### ISSUE TITLE
Zero runtime dependency translation module

### ISSUE THREAD

**Issue by eliocamp** [eliocamp/rhelpi18n#17]
Thinking about #14, I feel that it would be better if translation modules didn't have any (runtime) dependency on rhelpi18n. Otherwise we would need to think very carefully about backwards compatibility.

**Comment by cregouby** [comment]
currently usage for the {module.lang} package mandates
```r
library(rhelpi18n)   # very easy to forget name / loading order
library(tabnet.fr)   # very easy to remember as I make a lot of marketing and communication around it 
??autoplot.tabnet_explain
```

whereas I'd love my users to not care about the {rhelpi18n} package and just think of the translation package : 

```r
library(tabnet.fr)
??autoplot.tabnet_explain
```

It can be done through inserting
```r
.onLoad <- function(libname, pkgname){
  utils <- asNamespace('utils')
  
  package_env <- as.environment('package:utils')
  rhelpi18n:::sudo_assignInNamespace(".getHelpFile", utils:::.getHelpFile, ns = utils, envir = package_env)
}
```
as a slightly modified /R/zzzz.R  in the module.lang package, but doesn't pass R CMD check...

**Comment by eliocamp** [comment]
It's not necessary to load the translation module. 

This works

```r
library(rhelpi18n)
??autoplot.tabnet_explain
```

The expectation for now would be that users would put `library(rhelpi18n)` on their .Rprofile so it's always active. 

This issue is that translation modules use rhelpi18n to load the translations with `rhelpi18n::read_translations()`. I believe that the way is currently implemented, this makes `rhelpi18n` a build dependency of translation modules, which means that updates to `read_translations()` can potentially break development of previous translation modules.

**Comment by cregouby** [comment]
Thanks for pointing this to me, I didn't get it. I'll update the README to clarify this.

For the supporting the future updates of `read_translations()`, we will perhaps be able to manage a version tag in DESCRIPTION file ([the way testthat does](https://github.com/r-lib/testthat/blob/f060ccec365e1343ae926c53c215a423b295d7a8/R/edition.R#L1)) 
```r
Config/rhelpi18n/edition: 2
Config/testthat/edition: 3
```

**Comment by eliocamp** [comment]
That would require us to potentially maintain multiple overlapping sets of functionality. I don't think it's worth it. 

Beside, offloading code to the translation module would enable translation modules to potentially do other stuff that is particularly relevant to their language/community.
