### ISSUE TITLE
Add translator information to DESCRIPTION 

### ISSUE THREAD

**Issue by eliocamp** [eliocamp/rhelpi18n#22]
Idea from Christophe

**Comment by cregouby** [comment]
Hello @eliocamp 
Thanks for collecting this here !

Idea covers two cases

- I'm a package maintainer, I have the opportunity to have my {package} translated thanks to the opportunistic collaboration available with my teammate / student / daughter  / ... that is native in the EO language and proficient in the usage of {package} so I prepare the {package-EO} and I provide him/her <...> for the translation part.

- I want to organize the translation of a major package like {data.table} and share the effort within the local R user group, so I initiate the {data.table-FR} package and want to split the load into the 5 translator participants.
